#!/bin/sh
cat "$2" > "$3"
grep 'Parser p' "$2" | sed 's/Parser p => //g;s/ p / Acceptor /g;s/^/{-# SPECIALISE /;s/$/ #-}/' >> "$3"
grep 'Parser p' "$2" | sed 's/Parser p => //g;s/ p / Reporter /g;s/^/{-# SPECIALISE /;s/$/ #-}/' >> "$3"
