name: paripari
version: 0.3.0.0
synopsis: Parser combinators with fast-path and slower fallback for error reporting
description: PariPari offers two parsing strategies. There is a fast Acceptor and a slower Reporter which are evaluated in parallel. If the Acceptor fails, the Reporter returns a report about the parsing errors. Like Attoparsec, the parser combinators backtrack by default.
category: Text
stability: experimental
author: Daniel Mendler <mail@daniel-mendler.de>
maintainer: Daniel Mendler <mail@daniel-mendler.de>
copyright: 2018 Daniel Mendler
license: MIT
github: minad/paripari

tested-with:
  GHC == 8.0.1,
  GHC == 8.2.1,
  GHC == 8.4.3,
  GHC == 8.6.1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wmonomorphism-restriction
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wtabs
- -fprint-potential-instances

dependencies:
- base               >= 4.8  && < 5
- text               >= 0.11 && < 1.3
- bytestring         >= 0.10 && < 0.11
- parser-combinators >= 1.0  && < 1.1

library:
  source-dirs: src

executables:
  paripari-specialise-all:
    main: specialise-all.hs
    dependencies: paripari
  paripari-example:
    main: example.hs
    dependencies: paripari

tests:
  test:
    source-dirs:   test
    main:          test.hs
    dependencies:
      - paripari
      - random
      - tasty
      - tasty-hunit
