name: paripari
version: 0.1.0.0
synopsis: Fast parser combinator library with two strategies (Fast acceptor and slower error reporter)
description: PariPari offers two parsing strategies. There is a fast Acceptor and a slower Reporter which are evaluated in parallel. If the Acceptor fails, the Reporter returns a report about the parsing errors. Unlike Parsec and like Attoparsec, the parser combinators backtrack by default.
category: Text
stability: experimental
author: Daniel Mendler <mail@daniel-mendler.de>
maintainer: Daniel Mendler <mail@daniel-mendler.de>
copyright: 2018 Daniel Mendler
license: MIT
github: minad/paripari

tested-with:
  GHC == 8.2.1,
  GHC == 8.4.3,
  GHC == 8.6.1

default-extensions:
- BangPatterns
- GeneralizedNewtypeDeriving
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- Rank2Types

ghc-options:
- -Wall
- -Widentities
- -Wmonomorphism-restriction
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wtabs
- -fprint-potential-instances

dependencies:
- base               >= 4.8  && < 5
- text               >= 0.11 && < 1.3
- bytestring         >= 0.10 && < 0.11
- parser-combinators >= 1.0  && < 1.1

library:
  source-dirs: src

executables:
  example:
    main: example.hs
    dependencies: paripari
